name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.3
        
    - name: Test
      run: go test -v ./...

    - name: Build ceal win/amd64
      run: env GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o ceal_win_amd64.exe cmd/ceal/main.go

    - name: Build ceal linux/amd64
      run: env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ceal_linux_amd64 cmd/ceal/main.go

    - name: Build ceal darwin/amd64
      run: env GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o ceal_darwin_amd64 cmd/ceal/main.go

    - name: Build ceal darwin/arm64
      run: env GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -o ceal_darwin_arm64 cmd/ceal/main.go

    - name: Prepare version file
      run: echo $GITHUB_SHA > version

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: dev
        artifacts: "avm.hpp,ceal_win_amd64.exe,ceal_linux_amd64,ceal_darwin_amd64,ceal_darwin_arm64"
        prerelease: true
